#!/usr/bin/env node
import { cpSync, mkdirSync, existsSync, rmSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const dist = resolve(root, 'dist')
const gameDir = resolve(dist, 'skippity')

mkdirSync(dist, { recursive: true })

// Static landing at site root (portal/ stays out of Vite's way)
cpSync(resolve(root, 'portal/index.html'), resolve(dist, 'index.html'))
cpSync(resolve(root, 'portal/landing.css'), resolve(dist, 'landing.css'))
cpSync(resolve(root, 'public/images'), resolve(dist, 'images'), { recursive: true })
cpSync(resolve(root, 'deploy/dreamhost.htaccess'), resolve(dist, '.htaccess'))

if (existsSync(gameDir)) {
  cpSync(
    resolve(root, 'deploy/skippity.htaccess'),
    resolve(gameDir, '.htaccess'),
  )
  cpSync(resolve(root, 'deploy/hit.php'), resolve(gameDir, 'hit.php'))
  // Seed only if missing — never overwrite a live stats page regenerated by hit.php
  const countPage = resolve(gameDir, 'count.html')
  if (!existsSync(countPage)) {
    cpSync(resolve(root, 'deploy/count.html'), countPage)
  }
}

// Drop leftover root assets from older builds (game assets live under /skippity/assets)
for (const leftover of ['assets', 'favicon.svg', 'icons.svg']) {
  const p = resolve(dist, leftover)
  if (existsSync(p)) rmSync(p, { recursive: true, force: true })
}

console.log('Assembled dist/: static landing + /skippity game')
